ci: don't run lava test if required var CI_LAVA_TOKEN not set
CI_LAVA_TOKEN is required for submitting job to LAVA server. It should
be set in instance level gitlab CI/CD variables for testing forking dev
flow based MRs.

With `when: never` rule, test job will not be added to pipeline if the
above var not set. If the condition not set in test job that extends
`.lava-test`, `.lava-test` will ask user to do so and then exit with
unsuccessful job status. There is no easy way to exit early with
successful status yet. See
https://gitlab.com/gitlab-org/gitlab/-/issues/329217#note_572963049

Adding the above condition in `.lava-test` has no impact on test job
that extends the `.lava-test`.

Signed-off-by: Chase Qi <chase.qi@linaro.org>

diff --git a/.oniro-ci/test-generic.yaml b/.oniro-ci/test-generic.yaml
--- a/.oniro-ci/test-generic.yaml
+++ b/.oniro-ci/test-generic.yaml
@@ -8,7 +8,12 @@
   interruptible: true
   image:
     name: registry.ostc-eu.org/ostc/containers/ostc-builder:latest
+  variables:
+    CI_LAVA_INSTANCE: "https://lava.ostc-eu.org/"
   before_script:
+    - test -n "$CI_LAVA_TOKEN" || (
+        echo "precondition failed - please disable the child job if CI_LAVA_TOKEN not set in gitlab CI/CD variables"
+        && exit 1 )
     # Check if the job is configured properly.
     - test -n "$CI_LAVA_JOB_DEFINITION" || (
         echo "precondition failed - set CI_LAVA_JOB_DEFINITION to the URL of the LAVA test job definition"
@@ -77,6 +82,8 @@
   image:
     name: registry.ostc-eu.org/ostc/containers/ostc-builder:latest
   stage: report
+  variables:
+    CI_LAVA_INSTANCE: "https://lava.ostc-eu.org/"
   script:
     - |
       for file in $(find ./ -name "job_ids_*.txt"); do
